stages:
  - deps
  - lint
  - test

# Common setup for all meteor based jobs
.meteor:
  image: hub.eole.education/proxyhub/geoffreybooth/meteor-base:2.5
  before_script:
    - cd app
  cache:
    paths:
      - app/node_modules/
  variables:
    METEOR_ALLOW_SUPERUSER: "true"
  rules:
    - if: '$CI_COMMIT_MESSAGE  !~ /^(\[Draft\]|\(Draft\)|Draft:|\[WIP\]|WIP:)/'


###############################################################################
# `deps` stage: to download and cache dependencies
###############################################################################
cache-dependencies:
  stage: deps
  extends: .meteor
  script:
    - meteor npm ci && meteor npm install
  artifacts:
    paths:
      - app/node_modules/
    expire_in: 2 hrs


###############################################################################
# `lint` stage: `meteor-lint`
###############################################################################
meteor-lint:
  stage: lint
  extends: .meteor
  script:
    - meteor npm install --only=dev
    - meteor npm run lint


###############################################################################
# `test` stage: `meteor-tests`
###############################################################################
meteor-tests:
  stage: test
  extends: .meteor
  script:
    - meteor npm test
